# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sat Sep 17 13:23:58 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(564, 473)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter = QtGui.QSplitter(self.tab1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.inbox_remove_button = QtGui.QPushButton(self.tab1)
        self.inbox_remove_button.setObjectName(_fromUtf8("inbox_remove_button"))
        self.horizontalLayout_5.addWidget(self.inbox_remove_button)
        self.inbox_refresh_button = QtGui.QPushButton(self.tab1)
        self.inbox_refresh_button.setObjectName(_fromUtf8("inbox_refresh_button"))
        self.horizontalLayout_5.addWidget(self.inbox_refresh_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.inbox_mails_tableView = QtGui.QTableView(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inbox_mails_tableView.sizePolicy().hasHeightForWidth())
        self.inbox_mails_tableView.setSizePolicy(sizePolicy)
        self.inbox_mails_tableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.inbox_mails_tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.inbox_mails_tableView.setTextElideMode(QtCore.Qt.ElideLeft)
        self.inbox_mails_tableView.setObjectName(_fromUtf8("inbox_mails_tableView"))
        self.horizontalLayout_3.addWidget(self.inbox_mails_tableView)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.tab1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.inbox_from_lineEdit = QtGui.QLineEdit(self.tab1)
        self.inbox_from_lineEdit.setReadOnly(True)
        self.inbox_from_lineEdit.setObjectName(_fromUtf8("inbox_from_lineEdit"))
        self.horizontalLayout_6.addWidget(self.inbox_from_lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.tab1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.inbox_to_lineEdit = QtGui.QLineEdit(self.tab1)
        self.inbox_to_lineEdit.setReadOnly(True)
        self.inbox_to_lineEdit.setObjectName(_fromUtf8("inbox_to_lineEdit"))
        self.horizontalLayout_7.addWidget(self.inbox_to_lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.tab1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.inbox_subject_lineEdit = QtGui.QLineEdit(self.tab1)
        self.inbox_subject_lineEdit.setReadOnly(True)
        self.inbox_subject_lineEdit.setObjectName(_fromUtf8("inbox_subject_lineEdit"))
        self.horizontalLayout_8.addWidget(self.inbox_subject_lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.inbox_body_textEdit = QtGui.QTextEdit(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inbox_body_textEdit.sizePolicy().hasHeightForWidth())
        self.inbox_body_textEdit.setSizePolicy(sizePolicy)
        self.inbox_body_textEdit.setReadOnly(True)
        self.inbox_body_textEdit.setObjectName(_fromUtf8("inbox_body_textEdit"))
        self.verticalLayout_8.addWidget(self.inbox_body_textEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tab2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.compose_from_lineEdit = QtGui.QLineEdit(self.tab2)
        self.compose_from_lineEdit.setObjectName(_fromUtf8("compose_from_lineEdit"))
        self.horizontalLayout.addWidget(self.compose_from_lineEdit)
        self.label_2 = QtGui.QLabel(self.tab2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.compose_to_lineEdit = QtGui.QLineEdit(self.tab2)
        self.compose_to_lineEdit.setObjectName(_fromUtf8("compose_to_lineEdit"))
        self.horizontalLayout.addWidget(self.compose_to_lineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.tab2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.compose_subject_lineEdit = QtGui.QLineEdit(self.tab2)
        self.compose_subject_lineEdit.setObjectName(_fromUtf8("compose_subject_lineEdit"))
        self.horizontalLayout_2.addWidget(self.compose_subject_lineEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(self.tab2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.compose_body_textEdit = QtGui.QTextEdit(self.tab2)
        self.compose_body_textEdit.setObjectName(_fromUtf8("compose_body_textEdit"))
        self.verticalLayout.addWidget(self.compose_body_textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.compose_send_button = QtGui.QPushButton(self.tab2)
        self.compose_send_button.setObjectName(_fromUtf8("compose_send_button"))
        self.horizontalLayout_4.addWidget(self.compose_send_button)
        self.compose_clear_button = QtGui.QPushButton(self.tab2)
        self.compose_clear_button.setObjectName(_fromUtf8("compose_clear_button"))
        self.horizontalLayout_4.addWidget(self.compose_clear_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.compose_status_label = QtGui.QLabel(self.tab2)
        self.compose_status_label.setObjectName(_fromUtf8("compose_status_label"))
        self.verticalLayout_3.addWidget(self.compose_status_label)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAlskgh = QtGui.QMenu(self.menubar)
        self.menuAlskgh.setObjectName(_fromUtf8("menuAlskgh"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSetting = QtGui.QAction(MainWindow)
        self.actionSetting.setObjectName(_fromUtf8("actionSetting"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuAlskgh.addSeparator()
        self.menuAlskgh.addAction(self.actionSetting)
        self.menuAlskgh.addAction(self.actionExit)
        self.menubar.addAction(self.menuAlskgh.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.inbox_refresh_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.inbox_refresh_button_click)
        QtCore.QObject.connect(self.inbox_remove_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.inbox_remove_button_click)
        QtCore.QObject.connect(self.compose_send_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.compose_send_button_click)
        QtCore.QObject.connect(self.compose_clear_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.compose_clear_button_click)
        QtCore.QObject.connect(self.inbox_mails_tableView, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), MainWindow.inbox_listView_click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.compose_from_lineEdit, self.compose_to_lineEdit)
        MainWindow.setTabOrder(self.compose_to_lineEdit, self.compose_subject_lineEdit)
        MainWindow.setTabOrder(self.compose_subject_lineEdit, self.compose_body_textEdit)
        MainWindow.setTabOrder(self.compose_body_textEdit, self.compose_send_button)
        MainWindow.setTabOrder(self.compose_send_button, self.compose_clear_button)
        MainWindow.setTabOrder(self.compose_clear_button, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.inbox_body_textEdit)
        MainWindow.setTabOrder(self.inbox_body_textEdit, self.inbox_mails_tableView)
        MainWindow.setTabOrder(self.inbox_mails_tableView, self.inbox_from_lineEdit)
        MainWindow.setTabOrder(self.inbox_from_lineEdit, self.inbox_to_lineEdit)
        MainWindow.setTabOrder(self.inbox_to_lineEdit, self.inbox_subject_lineEdit)
        MainWindow.setTabOrder(self.inbox_subject_lineEdit, self.inbox_refresh_button)
        MainWindow.setTabOrder(self.inbox_refresh_button, self.inbox_remove_button)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Email-clienet", None))
        self.inbox_remove_button.setText(_translate("MainWindow", "Remove", None))
        self.inbox_refresh_button.setText(_translate("MainWindow", "Refresh", None))
        self.label_6.setText(_translate("MainWindow", "From :", None))
        self.label_7.setText(_translate("MainWindow", "To :", None))
        self.label_8.setText(_translate("MainWindow", "Subject :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Inbox", None))
        self.label.setText(_translate("MainWindow", "From :", None))
        self.label_2.setText(_translate("MainWindow", "To :", None))
        self.label_3.setText(_translate("MainWindow", "Subject :", None))
        self.label_4.setText(_translate("MainWindow", "Body :", None))
        self.compose_send_button.setText(_translate("MainWindow", "Send", None))
        self.compose_clear_button.setText(_translate("MainWindow", "Clear", None))
        self.compose_status_label.setText(_translate("MainWindow", "status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Compose", None))
        self.menuAlskgh.setTitle(_translate("MainWindow", "menu", None))
        self.actionSetting.setText(_translate("MainWindow", "Setting", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

